# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0090_auto_20180619_1242'),
        ('pretixbase', '0095_auto_20180604_1129'),
    ]

    operations = [
    ]
